// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQutb_il8wv2r2jI4LuDmap33vFaZJwQM',
    appId: '1:90682575394:web:73f7bd65d08ffdb8fd587b',
    messagingSenderId: '90682575394',
    projectId: 'smart-iot-d1888',
    authDomain: 'smart-iot-d1888.firebaseapp.com',
    databaseURL: 'https://smart-iot-d1888-default-rtdb.firebaseio.com',
    storageBucket: 'smart-iot-d1888.firebasestorage.app',
    measurementId: 'G-YG6H5YDFJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4rUPIEyZx7IzbTq4mwYncVgP1Z6EDCDA',
    appId: '1:90682575394:android:4b5b522c50bc486afd587b',
    messagingSenderId: '90682575394',
    projectId: 'smart-iot-d1888',
    databaseURL: 'https://smart-iot-d1888-default-rtdb.firebaseio.com',
    storageBucket: 'smart-iot-d1888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtoIjvo4-i5DfxEI251xLitqWxq3IgQuc',
    appId: '1:90682575394:ios:ab9e57c9e77dac81fd587b',
    messagingSenderId: '90682575394',
    projectId: 'smart-iot-d1888',
    databaseURL: 'https://smart-iot-d1888-default-rtdb.firebaseio.com',
    storageBucket: 'smart-iot-d1888.firebasestorage.app',
    iosBundleId: 'com.example.smartIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtoIjvo4-i5DfxEI251xLitqWxq3IgQuc',
    appId: '1:90682575394:ios:ab9e57c9e77dac81fd587b',
    messagingSenderId: '90682575394',
    projectId: 'smart-iot-d1888',
    databaseURL: 'https://smart-iot-d1888-default-rtdb.firebaseio.com',
    storageBucket: 'smart-iot-d1888.firebasestorage.app',
    iosBundleId: 'com.example.smartIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQutb_il8wv2r2jI4LuDmap33vFaZJwQM',
    appId: '1:90682575394:web:650dc5e8389e41d8fd587b',
    messagingSenderId: '90682575394',
    projectId: 'smart-iot-d1888',
    authDomain: 'smart-iot-d1888.firebaseapp.com',
    databaseURL: 'https://smart-iot-d1888-default-rtdb.firebaseio.com',
    storageBucket: 'smart-iot-d1888.firebasestorage.app',
    measurementId: 'G-QEZH401PRF',
  );

}